version: '3.9'

services:
  rabbit-mq:
    image: rabbitmq:4.0-management
  service-a:
    build: ./ServiceA
  
  service-b:
    build: ./ServiceB
  
  gateway:
    build: ./Gateway
    ports:
      - "5003:8080"
    depends_on:
      - service-a
      - service-b
