services:
  rabbit-mq:
    image: rabbitmq:4.0-management
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 3s
      retries: 5
  
  feedback-service:
    build:
      context: .
      dockerfile: ./FeedbackService/Dockerfile
    depends_on:
      rabbit-mq:
        condition: service_healthy
        
  api-orders:
    build:
      context: OrdersService
    depends_on:
      rabbit-mq:
       condition: service_healthy
       
  gateway:
    build:
      context: .
      dockerfile: ./Gateway/Dockerfile
    ports:
      - "5003:8080"
    depends_on:
      - service-a
      - service-b
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SuperSafePass.123"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssqlMyDatabase

  inventory-service:
    build:
      context: InventoryService
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    environment:
      InventoryService_ConnectionString: "Server=sqlserver;Database=MyDatabase;User Id=sa;Password=SuperSafePass.123;TrustServerCertificate=True;"

volumes:
  sqlserver_data: