# This is a generated file. Not intended for manual editing.
services:
  gateway:
    build:
      context: "C:\\Users\\felix\\Documents\\GitHub\\Microservices"
      dockerfile: "./Gateway/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Gateway.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "gateway:dev"
    ports: []
    volumes:
    - "C:\\Users\\felix\\Documents\\GitHub\\Microservices\\Gateway:/app:rw"
    - "C:\\Users\\felix\\Documents\\GitHub\\Microservices:/src:rw"
    - "C:\\Users\\felix\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
  service-a:
    build:
      context: "C:\\Users\\felix\\Documents\\GitHub\\Microservices"
      dockerfile: "./ServiceA/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/ServiceA.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "servicea:dev"
    ports: []
    volumes:
    - "C:\\Users\\felix\\Documents\\GitHub\\Microservices\\ServiceA:/app:rw"
    - "C:\\Users\\felix\\Documents\\GitHub\\Microservices:/src:rw"
    - "C:\\Users\\felix\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
  service-b:
    build:
      context: "C:\\Users\\felix\\Documents\\GitHub\\Microservices"
      dockerfile: "./ServiceB/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/ServiceB.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "serviceb:dev"
    ports: []
    volumes:
    - "C:\\Users\\felix\\Documents\\GitHub\\Microservices\\ServiceB:/app:rw"
    - "C:\\Users\\felix\\Documents\\GitHub\\Microservices:/src:rw"
    - "C:\\Users\\felix\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
